/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SideNote
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/commentManager.ts
var CommentManager = class {
  // Minimum characters to create regex pattern
  constructor(comments) {
    this.MIN_TEXT_LENGTH = 3;
    this.comments = comments;
  }
  /**
   * Generate SHA256 hash of the selected text using Web Crypto API (mobile-compatible)
   * @param text The text to hash
   * @returns The hash string
   */
  async generateHashAsync(text) {
    try {
      const encoder = new TextEncoder();
      const data = encoder.encode(text);
      const hashBuffer = await crypto.subtle.digest("SHA-256", data);
      const hashArray = Array.from(new Uint8Array(hashBuffer));
      const hashHex = hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
      return hashHex;
    } catch (error) {
      console.warn("Web Crypto API failed, using simple hash", error);
      let hash = 0;
      for (let i = 0; i < text.length; i++) {
        const char = text.charCodeAt(i);
        hash = (hash << 5) - hash + char;
        hash = hash & hash;
      }
      return Math.abs(hash).toString(16);
    }
  }
  /**
   * Synchronous hash generation for backward compatibility
   * Uses Web Crypto API when available, falls back to Node.js crypto
   */
  generateHash(text) {
    try {
      const nodeCrypto = require("crypto");
      return nodeCrypto.createHash("sha256").update(text).digest("hex");
    } catch (e) {
      let hash = 0;
      for (let i = 0; i < text.length; i++) {
        const char = text.charCodeAt(i);
        hash = (hash << 5) - hash + char;
        hash = hash & hash;
      }
      return Math.abs(hash).toString(16);
    }
  }
  getCommentsForFile(filePath) {
    return this.comments.filter((comment) => comment.filePath === filePath);
  }
  addComment(newComment) {
    if (!newComment.selectedTextHash) {
      newComment.selectedTextHash = this.generateHash(newComment.selectedText);
    }
    this.comments.push(newComment);
  }
  editComment(id, newCommentText) {
    const commentToEdit = this.comments.find((comment) => comment.id === id);
    if (commentToEdit) {
      commentToEdit.comment = newCommentText;
    }
  }
  deleteComment(id) {
    const indexToDelete = this.comments.findIndex((comment) => comment.id === id);
    if (indexToDelete > -1) {
      this.comments.splice(indexToDelete, 1);
    }
  }
  /**
   * Mark a comment as resolved (hidden but preserved for audit trail)
   * @param id The id of the comment to resolve
   */
  resolveComment(id) {
    const comment = this.comments.find((c) => c.id === id);
    if (comment) {
      comment.resolved = true;
      comment.resolvedAt = Date.now();
    }
  }
  /**
   * Mark a comment as unresolved (reopened)
   * @param id The id of the comment to unresolve
   */
  unresolveComment(id) {
    const comment = this.comments.find((c) => c.id === id);
    if (comment) {
      comment.resolved = false;
      comment.resolvedAt = null;
    }
  }
  /**
   * Delete all orphaned comments
   * @returns The number of orphaned comments deleted
   */
  deleteOrphanedComments() {
    const initialLength = this.comments.length;
    for (let i = this.comments.length - 1; i >= 0; i--) {
      if (this.comments[i].isOrphaned) {
        this.comments.splice(i, 1);
      }
    }
    return initialLength - this.comments.length;
  }
  /**
   * Get all orphaned comments
   * @returns Array of orphaned comments
   */
  getOrphanedComments() {
    return this.comments.filter((comment) => comment.isOrphaned);
  }
  /**
   * Get the count of orphaned comments
   * @returns Number of orphaned comments
   */
  getOrphanedCommentCount() {
    return this.comments.filter((comment) => comment.isOrphaned).length;
  }
  renameFile(oldPath, newPath) {
    this.comments.forEach((comment) => {
      if (comment.filePath === oldPath) {
        comment.filePath = newPath;
      }
    });
  }
  updateComments(newComments) {
    this.comments = newComments;
  }
  getComments() {
    return this.comments;
  }
  /**
   * Calculate distance between two positions (for finding closest match)
   * @param line1 First line number
   * @param char1 First character position
   * @param line2 Second line number
   * @param char2 Second character position
   * @returns Distance score (lower is closer)
   */
  calculateDistance(line1, char1, line2, char2) {
    const lineDistance = Math.abs(line1 - line2);
    const charDistance = Math.abs(char1 - char2);
    return lineDistance * 1e3 + charDistance;
  }
  /**
   * Find text position with hash verification for accuracy
   * Strategy 1: Search around hint coordinates and verify hash match
   * When multiple matches exist, returns the one closest to the hint coordinates
   * @param fileContent The current file content
   * @param selectedText The text to find
   * @param selectedTextHash The hash of the selected text
   * @param hintStartLine Starting line as a hint
   * @param hintStartChar Starting character as a hint
   * @param hintEndLine Ending line as a hint
   * @returns Object with line, startChar, endChar or null if not found
   */
  findTextPositionWithHashVerification(fileContent, selectedText, selectedTextHash, hintStartLine, hintStartChar, hintEndLine) {
    if (!selectedText || selectedText.length < this.MIN_TEXT_LENGTH) {
      return null;
    }
    const lines = fileContent.split("\n");
    const escapedText = selectedText.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const regex = new RegExp(escapedText, "g");
    const startLine = Math.max(0, hintStartLine - 10);
    const endLine = Math.min(lines.length, hintEndLine + 10);
    let candidates = [];
    for (let lineNum = startLine; lineNum < endLine; lineNum++) {
      let match;
      regex.lastIndex = 0;
      while ((match = regex.exec(lines[lineNum])) !== null) {
        const foundText = lines[lineNum].substring(match.index, match.index + selectedText.length);
        if (this.generateHash(foundText) === selectedTextHash) {
          const distance = this.calculateDistance(lineNum, match.index, hintStartLine, hintStartChar);
          candidates.push({
            line: lineNum,
            startChar: match.index,
            endChar: match.index + selectedText.length,
            distance
          });
        }
      }
    }
    if (candidates.length > 0) {
      candidates.sort((a, b) => a.distance - b.distance);
      const closest = candidates[0];
      return {
        line: closest.line,
        startChar: closest.startChar,
        endChar: closest.endChar
      };
    }
    return null;
  }
  /**
   * Find text by hash across the entire file
   * Strategy 2: Search entire file for matching hash using optimized approach
   * When multiple matches exist, returns the one closest to the hint coordinates
   * @param fileContent The current file content
   * @param selectedTextHash The hash to match
   * @param originalTextLength The length of the original selected text (optimization hint)
   * @param hintStartLine Starting line hint for proximity scoring
   * @param hintStartChar Starting character hint for proximity scoring
   * @returns Object with line, startChar, endChar, text or null if not found
   */
  findTextByHashOptimized(fileContent, selectedTextHash, originalTextLength, hintStartLine, hintStartChar) {
    const lines = fileContent.split("\n");
    let candidates = [];
    for (let lineNum = 0; lineNum < lines.length; lineNum++) {
      const line = lines[lineNum];
      if (line.length >= originalTextLength) {
        for (let startChar = 0; startChar <= line.length - originalTextLength; startChar++) {
          const candidate = line.substring(startChar, startChar + originalTextLength);
          if (this.generateHash(candidate) === selectedTextHash) {
            const distance = hintStartLine !== void 0 && hintStartChar !== void 0 ? this.calculateDistance(lineNum, startChar, hintStartLine, hintStartChar) : 0;
            candidates.push({
              line: lineNum,
              startChar,
              endChar: startChar + originalTextLength,
              text: candidate,
              distance
            });
          }
        }
      }
      const minLength = Math.max(this.MIN_TEXT_LENGTH, Math.floor(originalTextLength * 0.8));
      const maxLength = Math.min(line.length, Math.ceil(originalTextLength * 1.2));
      for (let length = minLength; length <= maxLength; length++) {
        if (length === originalTextLength) continue;
        for (let startChar = 0; startChar <= line.length - length; startChar++) {
          const candidate = line.substring(startChar, startChar + length);
          if (this.generateHash(candidate) === selectedTextHash) {
            const distance = hintStartLine !== void 0 && hintStartChar !== void 0 ? this.calculateDistance(lineNum, startChar, hintStartLine, hintStartChar) : 0;
            candidates.push({
              line: lineNum,
              startChar,
              endChar: startChar + length,
              text: candidate,
              distance
            });
          }
        }
      }
    }
    if (candidates.length > 0) {
      candidates.sort((a, b) => a.distance - b.distance);
      const closest = candidates[0];
      return {
        line: closest.line,
        startChar: closest.startChar,
        endChar: closest.endChar,
        text: closest.text
      };
    }
    return null;
  }
  /**
   * Find the position of selected text in the current file content
   * Uses regex matching as a fallback to line-based positioning
   * When multiple matches exist, returns the one closest to hint coordinates
   * @param fileContent The current file content
   * @param selectedText The text to find
   * @param hintStartLine Optional starting line as a hint (performance optimization)
   * @param hintEndLine Optional ending line as a hint (performance optimization)
   * @param hintStartChar Optional starting character as a hint (performance optimization)
   * @returns Object with line, startChar, endChar or null if not found
   */
  findTextPosition(fileContent, selectedText, hintStartLine, hintEndLine, hintStartChar) {
    if (!selectedText || selectedText.length < this.MIN_TEXT_LENGTH) {
      return null;
    }
    const lines = fileContent.split("\n");
    const escapedText = selectedText.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const regex = new RegExp(escapedText, "g");
    let candidates = [];
    let startLine = 0;
    let endLine = lines.length;
    if (hintStartLine !== void 0 && hintEndLine !== void 0) {
      startLine = Math.max(0, hintStartLine - 10);
      endLine = Math.min(lines.length, hintEndLine + 10);
    }
    for (let lineNum = startLine; lineNum < endLine; lineNum++) {
      let match;
      regex.lastIndex = 0;
      while ((match = regex.exec(lines[lineNum])) !== null) {
        const distance = hintStartLine !== void 0 && hintStartChar !== void 0 ? this.calculateDistance(lineNum, match.index, hintStartLine, hintStartChar) : 0;
        candidates.push({
          line: lineNum,
          startChar: match.index,
          endChar: match.index + selectedText.length,
          distance
        });
      }
    }
    if (candidates.length > 0) {
      candidates.sort((a, b) => a.distance - b.distance);
      const closest = candidates[0];
      return {
        line: closest.line,
        startChar: closest.startChar,
        endChar: closest.endChar
      };
    }
    if (hintStartLine !== void 0 && hintEndLine !== void 0) {
      candidates = [];
      for (let lineNum = 0; lineNum < lines.length; lineNum++) {
        let match;
        regex.lastIndex = 0;
        while ((match = regex.exec(lines[lineNum])) !== null) {
          const distance = hintStartLine !== void 0 && hintStartChar !== void 0 ? this.calculateDistance(lineNum, match.index, hintStartLine, hintStartChar) : 0;
          candidates.push({
            line: lineNum,
            startChar: match.index,
            endChar: match.index + selectedText.length,
            distance
          });
        }
      }
      if (candidates.length > 0) {
        candidates.sort((a, b) => a.distance - b.distance);
        const closest = candidates[0];
        return {
          line: closest.line,
          startChar: closest.startChar,
          endChar: closest.endChar
        };
      }
    }
    return null;
  }
  /**
   * Update comment coordinates based on file content changes
   * Uses 3-stage hash-based matching strategy:
   * 1. Search near old coordinates with hash verification
   * 2. Search entire file by hash
   * 3. Mark as orphaned if not found
   * @param fileContent The current file content
   * @param filePath The path of the file that was changed
   */
  updateCommentCoordinatesForFile(fileContent, filePath) {
    const fileComments = this.comments.filter((comment) => comment.filePath === filePath);
    fileComments.forEach((comment) => {
      let newPosition = null;
      if (comment.selectedTextHash) {
        newPosition = this.findTextPositionWithHashVerification(
          fileContent,
          comment.selectedText,
          comment.selectedTextHash,
          comment.startLine,
          comment.startChar,
          comment.endLine
        );
      }
      if (!newPosition && comment.selectedTextHash && comment.selectedText) {
        const hashMatch = this.findTextByHashOptimized(
          fileContent,
          comment.selectedTextHash,
          comment.selectedText.length,
          comment.startLine,
          comment.startChar
        );
        if (hashMatch) {
          newPosition = hashMatch;
          comment.selectedText = hashMatch.text;
        }
      }
      if (!newPosition && !comment.selectedTextHash) {
        newPosition = this.findTextPosition(
          fileContent,
          comment.selectedText,
          comment.startLine,
          comment.endLine,
          comment.startChar
        );
      }
      if (newPosition) {
        comment.startLine = newPosition.line;
        comment.startChar = newPosition.startChar;
        comment.endLine = newPosition.line;
        comment.endChar = newPosition.endChar;
        comment.isOrphaned = false;
      } else {
        comment.isOrphaned = true;
      }
    });
  }
};

// src/main.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");

// src/core/markdownCommentBlocks.ts
function escapeRegex(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function buildMarkdownBlock(excerpt, body, commentId) {
  const safeExcerpt = excerpt || "(no excerpt)";
  return `## ${safeExcerpt}
<!-- side-note:${commentId} -->
${body}

---`;
}
function resolveExistingMarker(content, comment) {
  const idMarker = `<!-- side-note:${comment.id} -->`;
  if (content.includes(idMarker)) {
    return idMarker;
  }
  const legacyMarker = `<!-- side-note:${comment.timestamp} -->`;
  if (content.includes(legacyMarker)) {
    return legacyMarker;
  }
  return null;
}
function replaceMarkdownCommentBlock(content, comment, newBody) {
  const marker = resolveExistingMarker(content, comment);
  if (!marker) {
    return content;
  }
  const escapedMarker = escapeRegex(marker);
  const blockRegex = new RegExp(`(^|
)## .*?
${escapedMarker}
[^]*?(?=
---
|$)`, "m");
  if (!blockRegex.test(content)) {
    return content;
  }
  const replacement = buildMarkdownBlock(comment.selectedText, newBody, comment.id);
  return content.replace(blockRegex, replacement);
}
function removeMarkdownCommentBlock(content, comment) {
  const marker = resolveExistingMarker(content, comment);
  if (!marker) {
    return content;
  }
  const escapedMarker = escapeRegex(marker);
  const blockRegex = new RegExp(`(^|
)## .*?
${escapedMarker}
[^]*?(?:
---
|$)`, "m");
  if (!blockRegex.test(content)) {
    return content;
  }
  const updated = content.replace(blockRegex, "").trim();
  return updated.length ? `${updated}
` : "";
}

// src/core/modalActionBindings.ts
function bindModalActionHandlers(args) {
  const now = args.now || (() => Date.now());
  const handleCancel = () => {
    if (args.submitGuard.isSubmitting()) {
      return;
    }
    args.onCancelTriggered();
  };
  const handleSubmit = async () => {
    var _a;
    const triggerResult = args.submitGuard.tryConsumeTrigger(now());
    if (!triggerResult.accepted) {
      (_a = args.onDebounceSuppressed) == null ? void 0 : _a.call(args, triggerResult.deltaMs);
      return;
    }
    await args.onSubmitTriggered();
  };
  args.cancelButton.addEventListener("click", () => {
    handleCancel();
  }, false);
  args.cancelButton.addEventListener("touchstart", (event) => {
    event.preventDefault();
  }, false);
  args.cancelButton.addEventListener("touchend", (event) => {
    event.preventDefault();
    event.stopPropagation();
    handleCancel();
  }, false);
  args.submitButton.addEventListener("click", () => {
    void handleSubmit();
  }, false);
  args.submitButton.addEventListener("touchstart", (event) => {
    event.preventDefault();
  }, false);
  args.submitButton.addEventListener("touchend", (event) => {
    event.preventDefault();
    event.stopPropagation();
    void handleSubmit();
  }, false);
}

// src/core/submitExecutionGuard.ts
var SubmitExecutionGuard = class {
  constructor(debounceMs) {
    this.submitting = false;
    this.lastTriggerAt = 0;
    this.debounceMs = debounceMs;
  }
  tryConsumeTrigger(now) {
    const deltaMs = now - this.lastTriggerAt;
    if (this.lastTriggerAt !== 0 && deltaMs < this.debounceMs) {
      return { accepted: false, deltaMs };
    }
    this.lastTriggerAt = now;
    return { accepted: true, deltaMs };
  }
  tryStartSubmit() {
    if (this.submitting) {
      return false;
    }
    this.submitting = true;
    return true;
  }
  finishSubmit() {
    this.submitting = false;
  }
  isSubmitting() {
    return this.submitting;
  }
  reset() {
    this.submitting = false;
    this.lastTriggerAt = 0;
  }
};

// src/main.ts
async function generateHash(text) {
  try {
    const encoder = new TextEncoder();
    const data = encoder.encode(text);
    const hashBuffer = await crypto.subtle.digest("SHA-256", data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    const hashHex = hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
    return hashHex;
  } catch (error) {
    try {
      const nodeCrypto = require("crypto");
      return nodeCrypto.createHash("sha256").update(text).digest("hex");
    } catch (e) {
      new import_obsidian.Notice("Warning: Could not generate proper hash, using fallback");
      let hash = 0;
      for (let i = 0; i < text.length; i++) {
        const char = text.charCodeAt(i);
        hash = (hash << 5) - hash + char;
        hash = hash & hash;
      }
      return Math.abs(hash).toString(16);
    }
  }
}
function generateCommentId() {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  try {
    const nodeCrypto = require("crypto");
    if (typeof nodeCrypto.randomUUID === "function") {
      return nodeCrypto.randomUUID();
    }
  } catch (e) {
  }
  return `sn-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}
var forceUpdateEffect = import_state.StateEffect.define();
var DEFAULT_SETTINGS = {
  commentSortOrder: "position",
  showHighlights: true,
  markdownFolder: "side-note-comments",
  highlightColor: "#FFC800",
  highlightOpacity: 0.2,
  showResolvedComments: false
};
var SideNoteView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin, file = null) {
    super(leaf);
    this.file = null;
    this.activeCommentId = null;
    this.showAllNotes = false;
    this.plugin = plugin;
    this.file = file;
  }
  getViewType() {
    return "sidenote-view";
  }
  getDisplayText() {
    return "Side Note";
  }
  getIcon() {
    return "message-square";
  }
  async onOpen() {
    await Promise.resolve();
    if (!this.file) {
      this.file = this.app.workspace.getActiveFile();
    }
    this.renderComments();
  }
  async setState(state, result) {
    if (state.filePath) {
      const file = this.app.vault.getAbstractFileByPath(state.filePath);
      if (file instanceof import_obsidian.TFile) {
        this.file = file;
        this.renderComments();
      }
    }
    await super.setState(state, result);
  }
  /**
   * Update view to show comments for a specific file
   * Called when active file changes
   */
  updateActiveFile(file) {
    this.file = file;
    this.renderComments();
  }
  /**
   * Highlight and scroll to a specific comment
   */
  highlightComment(commentId) {
    this.activeCommentId = commentId;
    this.renderComments();
    setTimeout(() => {
      const commentEl = this.containerEl.querySelector(`[data-comment-id="${commentId}"]`);
      if (commentEl) {
        commentEl.scrollIntoView({ behavior: "smooth", block: "center" });
      }
    }, 100);
  }
  setShowAllNotes(value) {
    this.showAllNotes = value;
    this.renderComments();
  }
  renderCommentItem(container, comment) {
    const commentEl = container.createDiv("sidenote-comment-item");
    commentEl.setAttribute("data-comment-id", comment.id);
    if (comment.resolved) {
      commentEl.addClass("resolved");
    }
    if (this.activeCommentId === comment.id) {
      commentEl.addClass("active");
    }
    const headerEl = commentEl.createDiv("sidenote-comment-header");
    const textInfoEl = headerEl.createDiv("sidenote-comment-text-info");
    textInfoEl.createEl("h4", { text: comment.selectedText, cls: "sidenote-selected-text" });
    textInfoEl.createEl("small", { text: new Date(comment.timestamp).toLocaleString(), cls: "sidenote-timestamp" });
    const actionsEl = headerEl.createDiv("sidenote-comment-actions");
    commentEl.onclick = async () => {
      let targetLeaf = null;
      this.app.workspace.iterateAllLeaves((leaf) => {
        var _a;
        if (leaf.view instanceof import_obsidian.MarkdownView && ((_a = leaf.view.file) == null ? void 0 : _a.path) === comment.filePath) {
          targetLeaf = leaf;
          return false;
        }
      });
      if (!targetLeaf) {
        const file = this.app.vault.getAbstractFileByPath(comment.filePath);
        if (file instanceof import_obsidian.TFile) {
          const newLeaf = this.app.workspace.getLeaf(true);
          await newLeaf.openFile(file);
          targetLeaf = newLeaf;
        }
      }
      if (targetLeaf && targetLeaf.view instanceof import_obsidian.MarkdownView) {
        this.app.workspace.setActiveLeaf(targetLeaf, { focus: true });
        const editor = targetLeaf.view.editor;
        editor.setSelection(
          { line: comment.startLine, ch: comment.startChar },
          { line: comment.endLine, ch: comment.endChar }
        );
        editor.scrollIntoView({
          from: { line: comment.startLine, ch: 0 },
          to: { line: comment.endLine, ch: 0 }
        }, true);
        editor.focus();
      } else {
        new import_obsidian.Notice("Failed to jump to Markdown view.");
      }
    };
    const contentWrapper = commentEl.createDiv({ cls: "sidenote-comment-content" });
    import_obsidian.MarkdownRenderer.renderMarkdown(
      comment.comment || "",
      contentWrapper,
      comment.filePath,
      this.plugin
    );
    contentWrapper.addEventListener("click", (event) => {
      const target = event.target;
      const link = target == null ? void 0 : target.closest("a.internal-link");
      if (!link) return;
      event.preventDefault();
      event.stopPropagation();
      const href = link.getAttribute("href") || link.getAttribute("data-href") || link.innerText;
      if (href) {
        this.app.workspace.openLinkText(href, comment.filePath, false);
      }
    });
    const menuButton = actionsEl.createEl("button", { text: "...", cls: "sidenote-menu-button" });
    const menuContainer = actionsEl.createDiv("sidenote-action-menu");
    const editOption = menuContainer.createEl("button", { text: "Edit", cls: "sidenote-menu-option sidenote-menu-edit" });
    editOption.onclick = (e) => {
      e.stopPropagation();
      menuContainer.classList.remove("visible");
      new CommentModal(this.app, async (editedComment) => {
        await this.plugin.editComment(comment.id, editedComment);
      }, comment.comment).open();
    };
    const deleteOption = menuContainer.createEl("button", { text: "Delete", cls: "sidenote-menu-option sidenote-menu-delete" });
    deleteOption.onclick = (e) => {
      e.stopPropagation();
      menuContainer.classList.remove("visible");
      new ConfirmDeleteModal(this.app, () => {
        this.plugin.deleteComment(comment.id);
      }).open();
    };
    const resolveOption = menuContainer.createEl("button", {
      text: comment.resolved ? "Reopen" : "Resolve",
      cls: "sidenote-menu-option sidenote-menu-resolve"
    });
    resolveOption.onclick = (e) => {
      e.stopPropagation();
      menuContainer.classList.remove("visible");
      if (comment.resolved) {
        this.plugin.unresolveComment(comment.id);
      } else {
        this.plugin.resolveComment(comment.id);
      }
    };
    menuButton.onclick = (e) => {
      e.stopPropagation();
      menuContainer.classList.toggle("visible");
    };
    document.addEventListener("click", () => {
      menuContainer.classList.remove("visible");
    });
  }
  renderComments() {
    this.containerEl.empty();
    this.containerEl.addClass("sidenote-view-container");
    const viewHeader = this.containerEl.createDiv("sidenote-view-header");
    const toggleBtn = viewHeader.createEl("button", {
      text: this.showAllNotes ? "Current File" : "All Notes",
      cls: "sidenote-view-toggle"
    });
    toggleBtn.onclick = () => {
      this.showAllNotes = !this.showAllNotes;
      this.renderComments();
    };
    if (this.showAllNotes) {
      this.renderAllNotesView();
      return;
    }
    if (this.file) {
      let commentsForFile = this.plugin.commentManager.getCommentsForFile(this.file.path);
      if (!this.plugin.settings.showResolvedComments) {
        commentsForFile = commentsForFile.filter((c) => !c.resolved);
      }
      if (this.plugin.settings.commentSortOrder === "position") {
        commentsForFile.sort((a, b) => {
          if (a.startLine === b.startLine) {
            return a.startChar - b.startChar;
          }
          return a.startLine - b.startLine;
        });
      } else {
        commentsForFile.sort((a, b) => a.timestamp - b.timestamp);
      }
      if (commentsForFile.length > 0) {
        const commentsContainer = this.containerEl.createDiv("sidenote-comments-container");
        commentsForFile.forEach((comment) => {
          this.renderCommentItem(commentsContainer, comment);
        });
      } else {
        const emptyStateEl = this.containerEl.createDiv("sidenote-empty-state");
        emptyStateEl.createEl("p", { text: "No comments for this file yet." });
        emptyStateEl.createEl("p", { text: "Select text in your note and use the 'add comment to selection' command to get started." });
      }
    } else {
      const emptyStateEl = this.containerEl.createDiv("sidenote-empty-state");
      emptyStateEl.createEl("p", { text: "No file selected." });
      emptyStateEl.createEl("p", { text: "Open a file to see its comments." });
    }
  }
  renderAllNotesView() {
    var _a, _b;
    let allComments = this.plugin.commentManager.getComments();
    if (!this.plugin.settings.showResolvedComments) {
      allComments = allComments.filter((c) => !c.resolved);
    }
    if (allComments.length === 0) {
      const emptyStateEl = this.containerEl.createDiv("sidenote-empty-state");
      emptyStateEl.createEl("p", { text: "No comments found across all notes." });
      return;
    }
    const byFile = /* @__PURE__ */ new Map();
    for (const comment of allComments) {
      const group = (_a = byFile.get(comment.filePath)) != null ? _a : [];
      group.push(comment);
      byFile.set(comment.filePath, group);
    }
    const commentsContainer = this.containerEl.createDiv("sidenote-comments-container");
    for (const [filePath, comments] of byFile) {
      const fileName = (_b = filePath.split("/").pop()) != null ? _b : filePath;
      const fileSection = commentsContainer.createDiv("sidenote-file-section");
      fileSection.createEl("h3", { text: fileName, cls: "sidenote-file-heading" });
      const sorted = [...comments];
      if (this.plugin.settings.commentSortOrder === "position") {
        sorted.sort((a, b) => a.startLine !== b.startLine ? a.startLine - b.startLine : a.startChar - b.startChar);
      } else {
        sorted.sort((a, b) => a.timestamp - b.timestamp);
      }
      for (const comment of sorted) {
        this.renderCommentItem(fileSection, comment);
      }
    }
  }
  getState() {
    return {
      filePath: this.file ? this.file.path : null
    };
  }
  onunload() {
  }
};
async function switchToSideNoteView(app) {
  const activeFile = app.workspace.getActiveFile();
  if (!activeFile) {
    new import_obsidian.Notice("No active Markdown file found.");
    return;
  }
  let leaf = null;
  try {
    leaf = app.workspace.getLeaf("split", "vertical");
  } catch (error) {
    new import_obsidian.Notice("Failed to create a new split view for comments.");
    console.error("Error creating split leaf:", error);
    return;
  }
  if (leaf) {
    await leaf.setViewState({
      type: "sidenote-view",
      state: { filePath: activeFile.path },
      // CustomViewState expects filePath
      active: true
      // Make the new view active
    });
    void app.workspace.revealLeaf(leaf);
  } else {
    new import_obsidian.Notice("Failed to create or find a leaf for the comment view.");
  }
}
var ConfirmDeleteModal = class extends import_obsidian.Modal {
  constructor(app, onConfirm) {
    super(app);
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("sidenote-confirm-modal");
    contentEl.createEl("h2", { text: "Delete comment" });
    contentEl.createEl("p", { text: "Are you sure you want to delete this comment? This action cannot be undone." });
    const footer = contentEl.createDiv("sidenote-modal-footer");
    const cancelButton = footer.createEl("button", {
      text: "Cancel",
      cls: "sidenote-modal-cancel-btn"
    });
    cancelButton.onclick = () => {
      this.close();
    };
    const deleteButton = footer.createEl("button", {
      text: "Delete",
      cls: "mod-warning sidenote-modal-submit-btn"
    });
    deleteButton.onclick = () => {
      this.onConfirm();
      this.close();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var CommentModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit, initialComment = "") {
    super(app);
    this.textareaEl = null;
    this.submitButtonEl = null;
    this.cancelButtonEl = null;
    this.submitGuard = new SubmitExecutionGuard(400);
    this.onSubmit = onSubmit;
    this.initialComment = initialComment;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("sidenote-comment-modal");
    contentEl.createEl("h2", { text: this.initialComment ? "Edit comment" : "Add comment" });
    const inputContainer = contentEl.createDiv("sidenote-comment-input-container");
    const input = inputContainer.createEl("textarea");
    input.placeholder = "Enter your comment...";
    input.value = this.initialComment;
    input.classList.add("sidenote-textarea");
    this.textareaEl = input;
    input.addEventListener("keydown", (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "Enter") {
        e.preventDefault();
        void this.submitComment();
      }
      if (e.key === "Escape") {
        e.preventDefault();
        if (!this.submitGuard.isSubmitting()) {
          this.close();
        }
      }
    });
    const footer = contentEl.createDiv("sidenote-modal-footer");
    const cancelButton = footer.createEl("button", {
      text: "Cancel",
      cls: "sidenote-modal-cancel-btn"
    });
    this.cancelButtonEl = cancelButton;
    const handleCancel = () => {
      this.close();
    };
    const submitButton = footer.createEl("button", {
      text: this.initialComment ? "Save" : "Add",
      cls: "mod-cta sidenote-modal-submit-btn"
    });
    this.submitButtonEl = submitButton;
    submitButton.setAttribute("type", "button");
    const handleSubmit = async () => {
      if (this.textareaEl) {
        this.textareaEl.blur();
      }
      await this.submitComment();
    };
    bindModalActionHandlers({
      submitButton,
      cancelButton,
      submitGuard: this.submitGuard,
      onSubmitTriggered: handleSubmit,
      onCancelTriggered: handleCancel
    });
    setTimeout(() => {
      input.focus();
      if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
        input.scrollIntoView({ behavior: "smooth", block: "center" });
      }
    }, 100);
    this.modalEl.addEventListener("click", (e) => {
      if (e.target === this.modalEl) {
        this.close();
      }
    });
    document.body.style.overflow = "hidden";
  }
  async submitComment() {
    if (!this.textareaEl) {
      new import_obsidian.Notice("Error: Comment field is empty");
      return;
    }
    if (!this.submitGuard.tryStartSubmit()) {
      return;
    }
    if (this.submitButtonEl) {
      this.submitButtonEl.disabled = true;
    }
    if (this.cancelButtonEl) {
      this.cancelButtonEl.disabled = true;
    }
    this.comment = this.textareaEl.value;
    try {
      await this.onSubmit(this.comment);
      this.close();
    } catch (error) {
      new import_obsidian.Notice("Error: Failed to save comment");
      console.error("Error in onSubmit:", error);
    } finally {
      this.submitGuard.finishSubmit();
      if (this.submitButtonEl) {
        this.submitButtonEl.disabled = false;
      }
      if (this.cancelButtonEl) {
        this.cancelButtonEl.disabled = false;
      }
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
    this.textareaEl = null;
    this.submitButtonEl = null;
    this.cancelButtonEl = null;
    this.submitGuard.reset();
    document.body.style.overflow = "";
  }
};
var SideNoteSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Comment sort order").setDesc("Choose how comments are sorted in the custom view.").addDropdown(
      (dropdown) => dropdown.addOption("timestamp", "By timestamp").addOption("position", "By position in file").setValue(this.plugin.settings.commentSortOrder).onChange(async (value) => {
        this.plugin.settings.commentSortOrder = value;
        await this.plugin.saveData();
        this.app.workspace.getLeavesOfType("sidenote-view").forEach((leaf) => {
          if (leaf.view instanceof SideNoteView) {
            leaf.view.renderComments();
          }
        });
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show highlights in editor").setDesc("Display highlights for commented text in the editor. After changing this setting, please restart Obsidian to see the effect.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showHighlights).onChange(async (value) => {
        this.plugin.settings.showHighlights = value;
        await this.plugin.saveData();
        this.plugin.refreshEditorDecorations();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show resolved comments").setDesc("Display resolved comments in the sidebar (shown dimmed). Uncheck to hide resolved comments entirely.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showResolvedComments).onChange(async (value) => {
        this.plugin.settings.showResolvedComments = value;
        await this.plugin.saveData();
        this.app.workspace.getLeavesOfType("sidenote-view").forEach((leaf) => {
          if (leaf.view instanceof SideNoteView) {
            leaf.view.renderComments();
          }
        });
      })
    );
    new import_obsidian.Setting(containerEl).setName("Highlight color").setDesc("Choose the color for highlighted comments in the editor").addColorPicker(
      (colorPicker) => colorPicker.setValue(this.plugin.settings.highlightColor || "#FFC800").onChange(async (value) => {
        this.plugin.settings.highlightColor = value;
        await this.plugin.saveData();
        this.plugin.applyHighlightColor();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Highlight opacity").setDesc("Set the transparency of the highlight (0 = transparent, 1 = opaque)").addSlider(
      (slider) => slider.setLimits(0, 1, 0.1).setValue(this.plugin.settings.highlightOpacity || 0.2).onChange(async (value) => {
        this.plugin.settings.highlightOpacity = value;
        await this.plugin.saveData();
        this.plugin.applyHighlightColor();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Markdown comments folder").setDesc("Folder (relative to vault) where sidenote markdown backup files are stored").addText(
      (text) => text.setPlaceholder("side-note-comments").setValue(this.plugin.settings.markdownFolder || "").onChange(async (value) => {
        this.plugin.settings.markdownFolder = value.trim() || "side-note-comments";
        await this.plugin.saveData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Create Markdown Backup").setDesc("Export all comments to markdown files in the configured folder").addButton(
      (button) => button.setButtonText("Create Backup").onClick(async () => {
        await this.plugin.migrateInlineCommentsToMarkdown();
        new import_obsidian.Notice("Markdown backup created successfully!");
      })
    );
    const orphanedCount = this.plugin.commentManager.getOrphanedCommentCount();
    new import_obsidian.Setting(containerEl).setName("Orphaned comments").setDesc(`There are ${orphanedCount} orphaned comment(s). These are comments whose original text was deleted.`);
    new import_obsidian.Setting(containerEl).addButton(
      (button) => button.setButtonText(`Delete ${orphanedCount} orphaned comment(s)`).setWarning().onClick(async () => {
        const deleted = this.plugin.commentManager.deleteOrphanedComments();
        await this.plugin.saveData();
        this.app.workspace.getLeavesOfType("sidenote-view").forEach((leaf) => {
          if (leaf.view instanceof SideNoteView) {
            leaf.view.renderComments();
          }
        });
        new import_obsidian.Notice(`Deleted ${deleted} orphaned comment(s)!`);
        this.display();
      }).setDisabled(orphanedCount === 0)
    );
  }
};
var SideNote = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.comments = [];
    this.editorUpdateTimers = {};
    this.duplicateAddWindowMs = 800;
    this.lastAddFingerprint = null;
  }
  registerFreshSettingTab() {
    var _a;
    const appWithSettings = this.app;
    const pluginTabs = (_a = appWithSettings.setting) == null ? void 0 : _a.pluginTabs;
    if (pluginTabs && pluginTabs[this.manifest.id]) {
      delete pluginTabs[this.manifest.id];
    }
    this.addSettingTab(new SideNoteSettingTab(this.app, this));
  }
  /** Ensure markdown comment folder exists and return normalized path */
  async ensureCommentFolder() {
    const folder = this.settings.markdownFolder.trim() || DEFAULT_SETTINGS.markdownFolder;
    const normalized = folder.replace(/^\/+|\/+$/g, "");
    const exists = await this.app.vault.adapter.exists(normalized);
    if (!exists) {
      await this.app.vault.createFolder(normalized);
    }
    return normalized;
  }
  /** Build side-note file path for a given note */
  getSideNoteFilePath(notePath) {
    const folder = this.settings.markdownFolder.trim() || DEFAULT_SETTINGS.markdownFolder;
    const normalized = folder.replace(/^\/+|\/+$/g, "");
    const base = notePath.replace(/\.md$/i, "").replace(/\//g, "__");
    return `${normalized}/${base}-sidenote.md`;
  }
  /** Build markdown block with marker */
  buildMarkdownBlock(excerpt, body, commentId) {
    return buildMarkdownBlock(excerpt, body, commentId);
  }
  /** Write or append comment to markdown file and return path */
  async writeCommentToMarkdown(notePath, excerpt, body, commentId) {
    const folder = await this.ensureCommentFolder();
    const filePath = this.getSideNoteFilePath(notePath);
    const block = this.buildMarkdownBlock(excerpt, body, commentId);
    const existing = this.app.vault.getAbstractFileByPath(filePath);
    if (existing instanceof import_obsidian.TFile) {
      const content = await this.app.vault.read(existing);
      const updated = content.trim().length === 0 ? block : `${content}

${block}`;
      await this.app.vault.modify(existing, updated);
    } else {
      const header = `# Side Notes for ${notePath}

`;
      await this.app.vault.create(filePath, `${header}${block}`);
    }
    return filePath;
  }
  /** Update markdown block by id (fallback to legacy timestamp marker) */
  async updateMarkdownComment(comment, newBody) {
    const filePath = comment.commentPath || this.getSideNoteFilePath(comment.filePath);
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (!(file instanceof import_obsidian.TFile)) return;
    const content = await this.app.vault.read(file);
    const updated = replaceMarkdownCommentBlock(content, comment, newBody);
    if (updated === content) return;
    await this.app.vault.modify(file, updated);
  }
  /** Delete markdown block by id (fallback to legacy timestamp marker) */
  async deleteMarkdownComment(comment) {
    const filePath = comment.commentPath || this.getSideNoteFilePath(comment.filePath);
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (!(file instanceof import_obsidian.TFile)) return;
    const content = await this.app.vault.read(file);
    const updated = removeMarkdownCommentBlock(content, comment);
    if (updated === content) return;
    await this.app.vault.modify(file, updated);
  }
  async onload() {
    await this.loadPluginData();
    this.commentManager = new CommentManager(this.comments);
    await this.migrateComments();
    this.registerEditorExtension([this.createHighlightPlugin()]);
    this.registerMarkdownPreviewHighlights();
    this.registerFreshSettingTab();
    this.registerView("sidenote-view", (leaf) => new SideNoteView(leaf, this));
    this.addCommand({
      id: "open-comment-view",
      name: "Open in Split View",
      callback: () => {
        void switchToSideNoteView(this.app);
      }
    });
    this.addCommand({
      id: "activate-view",
      name: "Open in Sidebar",
      callback: () => {
        this.activateView();
      }
    });
    this.addCommand({
      id: "view-all-comments",
      name: "View all comments",
      icon: "list",
      callback: async () => {
        await this.activateView();
        this.app.workspace.getLeavesOfType("sidenote-view").forEach((leaf) => {
          if (leaf.view instanceof SideNoteView) {
            leaf.view.setShowAllNotes(true);
          }
        });
      }
    });
    this.addCommand({
      id: "add-comment-to-selection",
      name: "Add comment to selection",
      icon: "message-square",
      editorCallback: async (editor, view) => {
        var _a;
        const selection = editor.getSelection();
        const cursorStart = editor.getCursor("from");
        const cursorEnd = editor.getCursor("to");
        const filePath = (_a = view.file) == null ? void 0 : _a.path;
        if (selection && selection.trim().length > 0 && filePath) {
          new CommentModal(this.app, async (comment) => {
            const selectedTextHash = await generateHash(selection);
            const newComment = {
              id: generateCommentId(),
              filePath,
              startLine: cursorStart.line,
              startChar: cursorStart.ch,
              endLine: cursorEnd.line,
              endChar: cursorEnd.ch,
              selectedText: selection,
              selectedTextHash,
              comment,
              timestamp: Date.now(),
              isOrphaned: false
            };
            await this.addComment(newComment);
          }).open();
        } else {
          new import_obsidian.Notice("Please select some text to add a comment.");
        }
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        if (editor.somethingSelected()) {
          menu.addItem((item) => {
            item.setTitle("Add comment to selection").setIcon("message-square").onClick(async () => {
              var _a;
              const selection = editor.getSelection();
              const cursorStart = editor.getCursor("from");
              const cursorEnd = editor.getCursor("to");
              const filePath = (_a = view.file) == null ? void 0 : _a.path;
              if (selection && selection.trim().length > 0 && filePath) {
                new CommentModal(this.app, async (comment) => {
                  const selectedTextHash = await generateHash(selection);
                  const newComment = {
                    id: generateCommentId(),
                    filePath,
                    startLine: cursorStart.line,
                    startChar: cursorStart.ch,
                    endLine: cursorEnd.line,
                    endChar: cursorEnd.ch,
                    selectedText: selection,
                    selectedTextHash,
                    comment,
                    timestamp: Date.now(),
                    isOrphaned: false
                  };
                  await this.addComment(newComment);
                }).open();
              } else {
                new import_obsidian.Notice("Please select some text to add a comment.");
              }
            });
          });
        }
      })
    );
    this.addRibbonIcon("message-square", "Side Note: Open in Sidebar", () => {
      this.activateView();
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if (leaf && leaf.view instanceof import_obsidian.MarkdownView) {
          const file = leaf.view.file;
          this.app.workspace.getLeavesOfType("sidenote-view").forEach((sideNoteLeaf) => {
            if (sideNoteLeaf.view instanceof SideNoteView) {
              sideNoteLeaf.view.updateActiveFile(file);
            }
          });
          this.refreshEditorDecorations();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian.TFile) {
          this.commentManager.renameFile(oldPath, file.path);
          void this.saveData();
          this.app.workspace.getLeavesOfType("sidenote-view").forEach((leaf) => {
            if (leaf.view instanceof SideNoteView) {
              leaf.view.renderComments();
            }
          });
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        var _a;
        if (file.path === ".obsidian/plugins/side-note/data.json" || file instanceof import_obsidian.TFile && file.name === "data.json" && ((_a = file.parent) == null ? void 0 : _a.name) === "side-note") {
          try {
            await this.loadPluginData();
            await this.migrateComments();
            this.commentManager.updateComments(this.comments);
            this.app.workspace.getLeavesOfType("sidenote-view").forEach((leaf) => {
              if (leaf.view instanceof SideNoteView) {
                leaf.view.renderComments();
              }
            });
          } catch (error) {
            console.error("Error reloading plugin data:", error);
          }
        } else if (file instanceof import_obsidian.TFile && file.extension === "md") {
          try {
            const fileContent = await this.app.vault.read(file);
            this.commentManager.updateCommentCoordinatesForFile(fileContent, file.path);
            await this.saveData();
            this.app.workspace.getLeavesOfType("sidenote-view").forEach((leaf) => {
              if (leaf.view instanceof SideNoteView) {
                leaf.view.renderComments();
              }
            });
          } catch (error) {
            console.error("Error updating comment coordinates:", error);
          }
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-change", (editor, info) => {
        var _a;
        const filePath = (_a = info == null ? void 0 : info.file) == null ? void 0 : _a.path;
        if (!filePath) return;
        const run = () => {
          try {
            this.refreshEditorDecorations();
          } catch (e) {
            console.warn("Failed to refresh decorations on editor-change", e);
          }
        };
        if (this.editorUpdateTimers[filePath]) {
          window.clearTimeout(this.editorUpdateTimers[filePath]);
        }
        this.editorUpdateTimers[filePath] = window.setTimeout(run, 250);
      })
    );
  }
  /**
   * Activate the Side Note view and highlight a specific comment
   */
  async activateViewAndHighlightComment(commentId) {
    await this.activateView();
    const leaves = this.app.workspace.getLeavesOfType("sidenote-view");
    leaves.forEach((leaf) => {
      if (leaf.view instanceof SideNoteView) {
        leaf.view.highlightComment(commentId);
      }
    });
  }
  /**
   * Activate the Side Note view - open it in the right sidebar if not already open
   */
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType("sidenote-view");
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({ type: "sidenote-view", active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
      if (leaf.view instanceof SideNoteView) {
        const activeFile = workspace.getActiveFile();
        leaf.view.updateActiveFile(activeFile);
      }
    }
  }
  async onCommentsChanged(message) {
    await this.saveData();
    this.app.workspace.getLeavesOfType("sidenote-view").forEach((leaf) => {
      if (leaf.view instanceof SideNoteView) {
        leaf.view.renderComments();
      }
    });
    this.refreshEditorDecorations();
    new import_obsidian.Notice(message);
  }
  createAddFingerprint(comment) {
    return [
      comment.filePath,
      comment.startLine,
      comment.startChar,
      comment.endLine,
      comment.endChar,
      comment.selectedText,
      comment.comment
    ].join("|");
  }
  async addComment(newComment) {
    const now = Date.now();
    const fingerprint = this.createAddFingerprint(newComment);
    if (this.lastAddFingerprint && this.lastAddFingerprint.key === fingerprint && now - this.lastAddFingerprint.at < this.duplicateAddWindowMs) {
      return;
    }
    this.lastAddFingerprint = { key: fingerprint, at: now };
    this.commentManager.addComment(newComment);
    await this.onCommentsChanged("Comment added!");
  }
  async editComment(commentId, newCommentText) {
    this.commentManager.editComment(commentId, newCommentText);
    await this.onCommentsChanged("Comment updated!");
  }
  async deleteComment(commentId) {
    this.commentManager.deleteComment(commentId);
    await this.onCommentsChanged("Comment deleted!");
  }
  async resolveComment(commentId) {
    this.commentManager.resolveComment(commentId);
    await this.onCommentsChanged("Comment resolved!");
  }
  async unresolveComment(commentId) {
    this.commentManager.unresolveComment(commentId);
    await this.onCommentsChanged("Comment reopened!");
  }
  async loadPluginData() {
    const loadedData = Object.assign({}, { comments: [] }, DEFAULT_SETTINGS, await this.loadData());
    this.settings = {
      commentSortOrder: loadedData.commentSortOrder || DEFAULT_SETTINGS.commentSortOrder,
      showHighlights: loadedData.showHighlights !== void 0 ? loadedData.showHighlights : DEFAULT_SETTINGS.showHighlights,
      markdownFolder: loadedData.markdownFolder || DEFAULT_SETTINGS.markdownFolder,
      highlightColor: loadedData.highlightColor || DEFAULT_SETTINGS.highlightColor,
      highlightOpacity: loadedData.highlightOpacity !== void 0 ? loadedData.highlightOpacity : DEFAULT_SETTINGS.highlightOpacity,
      showResolvedComments: loadedData.showResolvedComments !== void 0 ? loadedData.showResolvedComments : DEFAULT_SETTINGS.showResolvedComments
    };
    this.comments = loadedData.comments || [];
    this.applyHighlightColor();
  }
  /**
   * Migrate existing comments to add missing hashes and initialize flags
   */
  async migrateComments() {
    let needsSave = false;
    for (const comment of this.comments) {
      if (!comment.id) {
        comment.id = generateCommentId();
        needsSave = true;
      }
      if (!comment.selectedTextHash && comment.selectedText) {
        comment.selectedTextHash = await generateHash(comment.selectedText);
        needsSave = true;
      }
      if (comment.isOrphaned === void 0) {
        comment.isOrphaned = false;
        needsSave = true;
      }
    }
    if (needsSave) {
      await this.saveData();
      console.log("Migrated comments: backfilled ids/hashes and initialized flags");
    }
  }
  /**
   * Export existing inline comments to markdown files
   */
  async migrateInlineCommentsToMarkdown() {
    let changed = false;
    for (const comment of this.comments) {
      if (!comment.commentPath) {
        const path = await this.writeCommentToMarkdown(comment.filePath, comment.selectedText, comment.comment, comment.id);
        comment.commentPath = path;
        changed = true;
      }
    }
    if (changed) {
      await this.saveData();
    }
  }
  /**
   * Inject highlights into rendered Markdown (reading view only)
   * Skips Live Preview/editing modes to preserve context menu functionality.
   */
  registerMarkdownPreviewHighlights() {
    this.registerMarkdownPostProcessor((element, context) => {
      const previewContainer = element.closest(".markdown-preview-view");
      if (!previewContainer) {
        return;
      }
      if (!this.settings.showHighlights) return;
      const comments = this.commentManager.getCommentsForFile(context.sourcePath).filter((c) => !c.isOrphaned && !!c.selectedText);
      if (!comments.length) return;
      const textNodes = [];
      const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT);
      let offset = 0;
      while (walker.nextNode()) {
        const node = walker.currentNode;
        const value = node.nodeValue || "";
        if (!value.length) continue;
        const start = offset;
        const end = start + value.length;
        textNodes.push({ node, start, end });
        offset = end;
      }
      const fullText = textNodes.map((t) => t.node.nodeValue || "").join("");
      if (!fullText.length) return;
      const wraps = [];
      for (const comment of comments) {
        const target = comment.selectedText;
        if (!target) continue;
        const idx = fullText.indexOf(target);
        if (idx === -1) continue;
        wraps.push({
          start: idx,
          end: idx + target.length,
          comment
        });
      }
      if (!wraps.length) return;
      const findPos = (absolute) => {
        for (const entry of textNodes) {
          if (absolute >= entry.start && absolute <= entry.end) {
            return { node: entry.node, offsetInNode: absolute - entry.start };
          }
        }
        return null;
      };
      wraps.sort((a, b) => b.start - a.start);
      for (const wrap of wraps) {
        const startPos = findPos(wrap.start);
        const endPos = findPos(wrap.end);
        if (!startPos || !endPos) continue;
        try {
          const range = document.createRange();
          range.setStart(startPos.node, startPos.offsetInNode);
          range.setEnd(endPos.node, endPos.offsetInNode);
          const span = document.createElement("span");
          span.classList.add("sidenote-highlight", "sidenote-highlight-preview");
          span.dataset.commentId = wrap.comment.id;
          span.addEventListener("click", (event) => {
            if (event.button !== 0) return;
            void this.activateViewAndHighlightComment(wrap.comment.id);
          });
          span.addEventListener("contextmenu", () => {
          });
          range.surroundContents(span);
        } catch (e) {
          console.warn("Failed to wrap preview highlight", e);
          continue;
        }
      }
    });
  }
  /**
   * Apply highlight color settings by updating CSS variables
   */
  applyHighlightColor() {
    const root = document.documentElement;
    const color = this.settings.highlightColor;
    const opacity = this.settings.highlightOpacity;
    const rgb = this.hexToRgb(color);
    const rgbaColor = `rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, ${opacity})`;
    const rgbaHoverColor = `rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, ${Math.min(opacity + 0.15, 1)})`;
    const rgbaBorderColor = `rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, ${Math.min(opacity + 0.4, 1)})`;
    const rgbaOrphaned = `rgba(255, 100, 100, ${opacity})`;
    const rgbaOrphanedHover = `rgba(255, 100, 100, ${Math.min(opacity + 0.15, 1)})`;
    const rgbaOrphanedBorder = `rgba(255, 100, 100, ${Math.min(opacity + 0.35, 1)})`;
    root.style.setProperty("--sidenote-highlight-color", rgbaColor);
    root.style.setProperty("--sidenote-highlight-hover", rgbaHoverColor);
    root.style.setProperty("--sidenote-highlight-border", rgbaBorderColor);
    root.style.setProperty("--sidenote-orphaned-color", rgbaOrphaned);
    root.style.setProperty("--sidenote-orphaned-hover", rgbaOrphanedHover);
    root.style.setProperty("--sidenote-orphaned-border", rgbaOrphanedBorder);
    this.refreshEditorDecorations();
  }
  /**
   * Convert hex color to RGB object
   */
  hexToRgb(hex) {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? {
      r: parseInt(result[1], 16),
      g: parseInt(result[2], 16),
      b: parseInt(result[3], 16)
    } : { r: 255, g: 200, b: 0 };
  }
  async saveData() {
    const dataToSave = {
      ...this.settings,
      comments: this.comments
    };
    await super.saveData(dataToSave);
    this.refreshEditorDecorations();
  }
  /**
   * Refresh editor decorations for all open markdown views
   */
  refreshEditorDecorations() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (leaf.view instanceof import_obsidian.MarkdownView) {
        const editor = leaf.view.editor;
        if (editor && editor.cm) {
          const cm = editor.cm;
          if (cm.dispatch) {
            cm.dispatch({ effects: [forceUpdateEffect.of(null)] });
          }
        }
      }
    });
  }
  /**
   * Create ViewPlugin for highlighting comments in editor
   */
  createHighlightPlugin() {
    const plugin = this;
    return import_view.ViewPlugin.fromClass(class {
      constructor(view) {
        this.view = view;
        this.decorations = this.buildDecorations(view);
        this.view.dom.addEventListener("click", this.handleClick.bind(this));
      }
      destroy() {
        this.view.dom.removeEventListener("click", this.handleClick.bind(this));
      }
      handleClick(event) {
        const target = event.target;
        const highlight = target.closest(".sidenote-highlight");
        if (highlight) {
          const commentId = highlight.getAttribute("data-comment-id");
          if (commentId) {
            plugin.activateViewAndHighlightComment(commentId);
          }
        }
      }
      update(update) {
        if (update.docChanged || update.viewportChanged || update.transactions.some((tr) => tr.effects.some((e) => e.is(forceUpdateEffect)))) {
          this.decorations = this.buildDecorations(update.view);
        }
      }
      buildDecorations(view) {
        const builder = new import_state.RangeSetBuilder();
        if (!plugin.settings.showHighlights) {
          return builder.finish();
        }
        let filePath = null;
        plugin.app.workspace.iterateAllLeaves((leaf) => {
          if (leaf.view instanceof import_obsidian.MarkdownView && leaf.view.file) {
            const editor = leaf.view.editor;
            if (editor && editor.cm === view) {
              filePath = leaf.view.file.path;
            }
          }
        });
        if (!filePath) return builder.finish();
        const doc = view.state.doc;
        const decorationsArray = [];
        const comments = plugin.commentManager.getCommentsForFile(filePath);
        comments.forEach((comment) => {
          if (comment.resolved) {
            return;
          }
          try {
            const docText = doc.toString();
            let highlightFound = false;
            if (!comment.isOrphaned && comment.selectedText) {
              const idx = docText.indexOf(comment.selectedText);
              if (idx !== -1) {
                const from = idx;
                const to = idx + comment.selectedText.length;
                if (from >= 0 && to <= doc.length && from < to) {
                  decorationsArray.push({
                    from,
                    to,
                    decoration: import_view.Decoration.mark({
                      class: "sidenote-highlight",
                      attributes: {
                        "data-comment-id": comment.id
                      }
                    })
                  });
                  highlightFound = true;
                }
              }
            }
            if (!highlightFound && comment.selectedTextHash && !comment.isOrphaned) {
              const lines = docText.split("\n");
              for (let lineNum = 0; lineNum < lines.length; lineNum++) {
                const line = lines[lineNum];
                for (let startChar = 0; startChar < line.length; startChar++) {
                  const candidate = line.substring(startChar, startChar + comment.selectedText.length);
                  if (candidate.length === comment.selectedText.length) {
                    let hash = 0;
                    for (let i = 0; i < candidate.length; i++) {
                      hash = (hash << 5) - hash + candidate.charCodeAt(i);
                    }
                    if (Math.abs(hash).toString(16) === comment.selectedTextHash.substring(0, 8)) {
                      try {
                        const line_obj = doc.line(lineNum + 1);
                        const from = line_obj.from + startChar;
                        const to = from + comment.selectedText.length;
                        if (from >= 0 && to <= doc.length && from < to) {
                          decorationsArray.push({
                            from,
                            to,
                            decoration: import_view.Decoration.mark({
                              class: "sidenote-highlight",
                              attributes: {
                                "data-comment-id": comment.id
                              }
                            })
                          });
                          highlightFound = true;
                          break;
                        }
                      } catch (e) {
                      }
                    }
                  }
                }
                if (highlightFound) break;
              }
            }
            if (!highlightFound && !comment.isOrphaned) {
              try {
                const line = doc.line(comment.startLine + 1);
                const from = line.from + comment.startChar;
                const to = line.from + comment.endChar;
                if (from >= 0 && to <= doc.length && from < to) {
                  decorationsArray.push({
                    from,
                    to,
                    decoration: import_view.Decoration.mark({
                      class: "sidenote-highlight",
                      attributes: {
                        "data-comment-id": comment.id
                      }
                    })
                  });
                }
              } catch (e) {
              }
            }
            if (comment.isOrphaned) {
              try {
                const line = doc.line(comment.startLine + 1);
                const from = line.from + comment.startChar;
                const to = Math.min(from + 1, line.to);
                if (from >= 0 && to <= doc.length && from < to) {
                  decorationsArray.push({
                    from,
                    to,
                    decoration: import_view.Decoration.mark({
                      class: "sidenote-highlight orphaned",
                      attributes: {
                        "data-comment-id": comment.id
                      }
                    })
                  });
                }
              } catch (e) {
              }
            }
          } catch (e) {
            console.warn("Failed to create decoration for comment:", e);
          }
        });
        decorationsArray.sort((a, b) => a.from - b.from);
        decorationsArray.forEach(({ from, to, decoration }) => {
          builder.add(from, to, decoration);
        });
        return builder.finish();
      }
    }, {
      decorations: (v) => v.decorations
    });
  }
};


/* nosourcemap */